// Catálogo base ramo-por-aseguradora (fase 2.6) — derivado del Excel de la agencia.
// Se carga por workspace desde Configuración con el botón "Cargar catálogo base".

export type DisponibleRamo = 'si' | 'no' | 'condicionado'

export interface RamoAseguradoraSeed {
  aseguradora: string
  ramo: string
  disponible: DisponibleRamo
  nota: string | null
}

export const RAMOS_CATALOGO: string[] = [
  'PYME (TODO RIESGO)',
  'AUTOS INDIVIDUAL',
  'AUTOS COLECTIVOS',
  'copropiedades',
  'UTILITARIOS',
  'MAQUINARIA',
  'MOTO',
  'TRC',
  'DECENAL',
  'D&O',
  'IRF',
  'VIDA INDIVIDUAL',
  'VIDA GRUPO',
  'RC SERVIDORES PUBLICOS',
  'MANEJO',
  'RC CLINICAS  Y HOSPITALES',
  'CUMPLIMIENTO',
]

export const ASEGURADORAS_CATALOGO: string[] = [
  'SURA',
  'SBS',
  'MAPFRE',
  'BOLIVAR',
  'HDI',
  'ZURICH',
  'MUNDIAL',
  'SOLIDARIA',
  'BBVA',
  'CHUBB',
  'PREVISORA',
  'SEGUROS DEL ESTADO',
  'ALLIANZ',
  'AXA',
  'CONFIANZA',
  'COLMENA',
  'METLIFE',
  'SOLUNION',
  'EQUIDAD SEGUROS',
]

export const CATALOGO_RAMOS_BASE: RamoAseguradoraSeed[] = [
  { aseguradora: 'SURA', ramo: 'PYME (TODO RIESGO)', disponible: 'si', nota: null },
  { aseguradora: 'SURA', ramo: 'AUTOS INDIVIDUAL', disponible: 'si', nota: null },
  { aseguradora: 'SURA', ramo: 'copropiedades', disponible: 'no', nota: null },
  { aseguradora: 'SURA', ramo: 'UTILITARIOS', disponible: 'condicionado', nota: 'individual' },
  { aseguradora: 'SURA', ramo: 'MAQUINARIA', disponible: 'si', nota: null },
  { aseguradora: 'SURA', ramo: 'MOTO', disponible: 'si', nota: null },
  { aseguradora: 'SURA', ramo: 'TRC', disponible: 'si', nota: null },
  { aseguradora: 'SURA', ramo: 'DECENAL', disponible: 'si', nota: null },
  { aseguradora: 'SURA', ramo: 'D&O', disponible: 'si', nota: null },
  { aseguradora: 'SURA', ramo: 'IRF', disponible: 'si', nota: 'SI - solo privados' },
  { aseguradora: 'SURA', ramo: 'RC SERVIDORES PUBLICOS', disponible: 'no', nota: null },
  { aseguradora: 'SURA', ramo: 'MANEJO', disponible: 'si', nota: null },
  { aseguradora: 'SURA', ramo: 'RC CLINICAS  Y HOSPITALES', disponible: 'si', nota: 'SI - cliente vinculado' },
  { aseguradora: 'SURA', ramo: 'CUMPLIMIENTO', disponible: 'si', nota: null },
  { aseguradora: 'SBS', ramo: 'PYME (TODO RIESGO)', disponible: 'si', nota: null },
  { aseguradora: 'SBS', ramo: 'AUTOS INDIVIDUAL', disponible: 'si', nota: null },
  { aseguradora: 'SBS', ramo: 'copropiedades', disponible: 'si', nota: null },
  { aseguradora: 'SBS', ramo: 'UTILITARIOS', disponible: 'no', nota: null },
  { aseguradora: 'SBS', ramo: 'MAQUINARIA', disponible: 'si', nota: 'SI - MIN 3' },
  { aseguradora: 'SBS', ramo: 'MOTO', disponible: 'si', nota: null },
  { aseguradora: 'SBS', ramo: 'TRC', disponible: 'si', nota: null },
  { aseguradora: 'SBS', ramo: 'D&O', disponible: 'si', nota: null },
  { aseguradora: 'SBS', ramo: 'IRF', disponible: 'si', nota: null },
  { aseguradora: 'SBS', ramo: 'RC SERVIDORES PUBLICOS', disponible: 'no', nota: null },
  { aseguradora: 'SBS', ramo: 'RC CLINICAS  Y HOSPITALES', disponible: 'no', nota: null },
  { aseguradora: 'SBS', ramo: 'CUMPLIMIENTO', disponible: 'no', nota: null },
  { aseguradora: 'MAPFRE', ramo: 'PYME (TODO RIESGO)', disponible: 'si', nota: null },
  { aseguradora: 'MAPFRE', ramo: 'AUTOS INDIVIDUAL', disponible: 'si', nota: null },
  { aseguradora: 'MAPFRE', ramo: 'copropiedades', disponible: 'si', nota: null },
  { aseguradora: 'MAPFRE', ramo: 'UTILITARIOS', disponible: 'no', nota: null },
  { aseguradora: 'MAPFRE', ramo: 'MAQUINARIA', disponible: 'si', nota: null },
  { aseguradora: 'MAPFRE', ramo: 'MOTO', disponible: 'si', nota: null },
  { aseguradora: 'MAPFRE', ramo: 'TRC', disponible: 'si', nota: null },
  { aseguradora: 'MAPFRE', ramo: 'IRF', disponible: 'si', nota: null },
  { aseguradora: 'MAPFRE', ramo: 'RC CLINICAS  Y HOSPITALES', disponible: 'no', nota: null },
  { aseguradora: 'MAPFRE', ramo: 'CUMPLIMIENTO', disponible: 'no', nota: null },
  { aseguradora: 'BOLIVAR', ramo: 'PYME (TODO RIESGO)', disponible: 'si', nota: null },
  { aseguradora: 'BOLIVAR', ramo: 'AUTOS INDIVIDUAL', disponible: 'si', nota: null },
  { aseguradora: 'BOLIVAR', ramo: 'copropiedades', disponible: 'no', nota: null },
  { aseguradora: 'BOLIVAR', ramo: 'MAQUINARIA', disponible: 'si', nota: null },
  { aseguradora: 'BOLIVAR', ramo: 'MOTO', disponible: 'no', nota: null },
  { aseguradora: 'BOLIVAR', ramo: 'TRC', disponible: 'si', nota: null },
  { aseguradora: 'BOLIVAR', ramo: 'D&O', disponible: 'no', nota: null },
  { aseguradora: 'BOLIVAR', ramo: 'RC SERVIDORES PUBLICOS', disponible: 'no', nota: null },
  { aseguradora: 'BOLIVAR', ramo: 'MANEJO', disponible: 'condicionado', nota: 'SOLO PRIVADOS' },
  { aseguradora: 'BOLIVAR', ramo: 'CUMPLIMIENTO', disponible: 'si', nota: null },
  { aseguradora: 'HDI', ramo: 'PYME (TODO RIESGO)', disponible: 'si', nota: null },
  { aseguradora: 'HDI', ramo: 'AUTOS INDIVIDUAL', disponible: 'si', nota: null },
  { aseguradora: 'HDI', ramo: 'copropiedades', disponible: 'condicionado', nota: 'SOLO ZONAS COMUNES' },
  { aseguradora: 'HDI', ramo: 'UTILITARIOS', disponible: 'condicionado', nota: 'individual' },
  { aseguradora: 'HDI', ramo: 'MAQUINARIA', disponible: 'si', nota: 'SI - MIN 10' },
  { aseguradora: 'HDI', ramo: 'MOTO', disponible: 'si', nota: null },
  { aseguradora: 'HDI', ramo: 'TRC', disponible: 'si', nota: null },
  { aseguradora: 'HDI', ramo: 'D&O', disponible: 'si', nota: null },
  { aseguradora: 'HDI', ramo: 'CUMPLIMIENTO', disponible: 'no', nota: null },
  { aseguradora: 'ZURICH', ramo: 'PYME (TODO RIESGO)', disponible: 'si', nota: null },
  { aseguradora: 'ZURICH', ramo: 'AUTOS INDIVIDUAL', disponible: 'si', nota: null },
  { aseguradora: 'ZURICH', ramo: 'MAQUINARIA', disponible: 'si', nota: 'SI - MIN 3' },
  { aseguradora: 'ZURICH', ramo: 'MOTO', disponible: 'no', nota: null },
  { aseguradora: 'ZURICH', ramo: 'TRC', disponible: 'si', nota: null },
  { aseguradora: 'ZURICH', ramo: 'D&O', disponible: 'si', nota: null },
  { aseguradora: 'ZURICH', ramo: 'CUMPLIMIENTO', disponible: 'si', nota: null },
  { aseguradora: 'MUNDIAL', ramo: 'PYME (TODO RIESGO)', disponible: 'no', nota: null },
  { aseguradora: 'MUNDIAL', ramo: 'AUTOS INDIVIDUAL', disponible: 'no', nota: null },
  { aseguradora: 'MUNDIAL', ramo: 'MAQUINARIA', disponible: 'si', nota: null },
  { aseguradora: 'MUNDIAL', ramo: 'MOTO', disponible: 'no', nota: null },
  { aseguradora: 'MUNDIAL', ramo: 'TRC', disponible: 'si', nota: null },
  { aseguradora: 'MUNDIAL', ramo: 'DECENAL', disponible: 'si', nota: null },
  { aseguradora: 'MUNDIAL', ramo: 'D&O', disponible: 'si', nota: null },
  { aseguradora: 'MUNDIAL', ramo: 'IRF', disponible: 'si', nota: null },
  { aseguradora: 'MUNDIAL', ramo: 'RC SERVIDORES PUBLICOS', disponible: 'no', nota: null },
  { aseguradora: 'MUNDIAL', ramo: 'RC CLINICAS  Y HOSPITALES', disponible: 'no', nota: null },
  { aseguradora: 'MUNDIAL', ramo: 'CUMPLIMIENTO', disponible: 'si', nota: null },
  { aseguradora: 'SOLIDARIA', ramo: 'PYME (TODO RIESGO)', disponible: 'si', nota: null },
  { aseguradora: 'SOLIDARIA', ramo: 'AUTOS INDIVIDUAL', disponible: 'si', nota: null },
  { aseguradora: 'SOLIDARIA', ramo: 'MAQUINARIA', disponible: 'si', nota: 'SI - MIN 2' },
  { aseguradora: 'SOLIDARIA', ramo: 'MOTO', disponible: 'si', nota: null },
  { aseguradora: 'SOLIDARIA', ramo: 'TRC', disponible: 'si', nota: null },
  { aseguradora: 'SOLIDARIA', ramo: 'D&O', disponible: 'si', nota: null },
  { aseguradora: 'SOLIDARIA', ramo: 'IRF', disponible: 'si', nota: null },
  { aseguradora: 'SOLIDARIA', ramo: 'RC SERVIDORES PUBLICOS', disponible: 'si', nota: null },
  { aseguradora: 'SOLIDARIA', ramo: 'CUMPLIMIENTO', disponible: 'si', nota: null },
  { aseguradora: 'BBVA', ramo: 'PYME (TODO RIESGO)', disponible: 'si', nota: null },
  { aseguradora: 'BBVA', ramo: 'AUTOS INDIVIDUAL', disponible: 'no', nota: null },
  { aseguradora: 'BBVA', ramo: 'MOTO', disponible: 'no', nota: null },
  { aseguradora: 'BBVA', ramo: 'TRC', disponible: 'si', nota: null },
  { aseguradora: 'BBVA', ramo: 'D&O', disponible: 'no', nota: null },
  { aseguradora: 'BBVA', ramo: 'CUMPLIMIENTO', disponible: 'no', nota: null },
  { aseguradora: 'CHUBB', ramo: 'PYME (TODO RIESGO)', disponible: 'si', nota: null },
  { aseguradora: 'CHUBB', ramo: 'AUTOS INDIVIDUAL', disponible: 'no', nota: null },
  { aseguradora: 'CHUBB', ramo: 'MOTO', disponible: 'no', nota: null },
  { aseguradora: 'CHUBB', ramo: 'TRC', disponible: 'si', nota: null },
  { aseguradora: 'CHUBB', ramo: 'DECENAL', disponible: 'no', nota: null },
  { aseguradora: 'CHUBB', ramo: 'D&O', disponible: 'si', nota: null },
  { aseguradora: 'CHUBB', ramo: 'RC SERVIDORES PUBLICOS', disponible: 'si', nota: null },
  { aseguradora: 'CHUBB', ramo: 'RC CLINICAS  Y HOSPITALES', disponible: 'si', nota: null },
  { aseguradora: 'CHUBB', ramo: 'CUMPLIMIENTO', disponible: 'no', nota: null },
  { aseguradora: 'PREVISORA', ramo: 'PYME (TODO RIESGO)', disponible: 'si', nota: null },
  { aseguradora: 'PREVISORA', ramo: 'AUTOS INDIVIDUAL', disponible: 'si', nota: null },
  { aseguradora: 'PREVISORA', ramo: 'copropiedades', disponible: 'no', nota: 'NO solo renovaciones' },
  { aseguradora: 'PREVISORA', ramo: 'MOTO', disponible: 'no', nota: null },
  { aseguradora: 'PREVISORA', ramo: 'D&O', disponible: 'si', nota: null },
  { aseguradora: 'PREVISORA', ramo: 'CUMPLIMIENTO', disponible: 'si', nota: null },
  { aseguradora: 'SEGUROS DEL ESTADO', ramo: 'PYME (TODO RIESGO)', disponible: 'si', nota: null },
  { aseguradora: 'SEGUROS DEL ESTADO', ramo: 'AUTOS INDIVIDUAL', disponible: 'si', nota: null },
  { aseguradora: 'SEGUROS DEL ESTADO', ramo: 'UTILITARIOS', disponible: 'si', nota: null },
  { aseguradora: 'SEGUROS DEL ESTADO', ramo: 'MOTO', disponible: 'no', nota: null },
  { aseguradora: 'SEGUROS DEL ESTADO', ramo: 'TRC', disponible: 'si', nota: null },
  { aseguradora: 'SEGUROS DEL ESTADO', ramo: 'DECENAL', disponible: 'no', nota: null },
  { aseguradora: 'SEGUROS DEL ESTADO', ramo: 'D&O', disponible: 'condicionado', nota: 'CONDICIONADO' },
  { aseguradora: 'SEGUROS DEL ESTADO', ramo: 'CUMPLIMIENTO', disponible: 'si', nota: null },
  { aseguradora: 'ALLIANZ', ramo: 'PYME (TODO RIESGO)', disponible: 'si', nota: null },
  { aseguradora: 'ALLIANZ', ramo: 'AUTOS INDIVIDUAL', disponible: 'si', nota: null },
  { aseguradora: 'ALLIANZ', ramo: 'MOTO', disponible: 'si', nota: null },
  { aseguradora: 'ALLIANZ', ramo: 'RC SERVIDORES PUBLICOS', disponible: 'no', nota: null },
  { aseguradora: 'ALLIANZ', ramo: 'CUMPLIMIENTO', disponible: 'no', nota: null },
  { aseguradora: 'AXA', ramo: 'PYME (TODO RIESGO)', disponible: 'si', nota: null },
  { aseguradora: 'AXA', ramo: 'AUTOS INDIVIDUAL', disponible: 'si', nota: null },
  { aseguradora: 'AXA', ramo: 'copropiedades', disponible: 'condicionado', nota: 'SOLO ZONAS COMUNES' },
  { aseguradora: 'AXA', ramo: 'MOTO', disponible: 'si', nota: null },
  { aseguradora: 'AXA', ramo: 'TRC', disponible: 'si', nota: null },
  { aseguradora: 'AXA', ramo: 'DECENAL', disponible: 'si', nota: null },
  { aseguradora: 'AXA', ramo: 'D&O', disponible: 'si', nota: null },
  { aseguradora: 'AXA', ramo: 'RC SERVIDORES PUBLICOS', disponible: 'condicionado', nota: 'CONDICIONADO' },
  { aseguradora: 'AXA', ramo: 'CUMPLIMIENTO', disponible: 'si', nota: null },
  { aseguradora: 'CONFIANZA', ramo: 'PYME (TODO RIESGO)', disponible: 'no', nota: null },
  { aseguradora: 'CONFIANZA', ramo: 'AUTOS INDIVIDUAL', disponible: 'no', nota: null },
  { aseguradora: 'CONFIANZA', ramo: 'MAQUINARIA', disponible: 'no', nota: null },
  { aseguradora: 'CONFIANZA', ramo: 'MOTO', disponible: 'no', nota: null },
  { aseguradora: 'CONFIANZA', ramo: 'TRC', disponible: 'si', nota: null },
  { aseguradora: 'CONFIANZA', ramo: 'D&O', disponible: 'si', nota: null },
  { aseguradora: 'CONFIANZA', ramo: 'CUMPLIMIENTO', disponible: 'si', nota: null },
  { aseguradora: 'COLMENA', ramo: 'PYME (TODO RIESGO)', disponible: 'no', nota: null },
  { aseguradora: 'COLMENA', ramo: 'AUTOS INDIVIDUAL', disponible: 'no', nota: null },
  { aseguradora: 'COLMENA', ramo: 'MAQUINARIA', disponible: 'no', nota: null },
  { aseguradora: 'COLMENA', ramo: 'MOTO', disponible: 'no', nota: null },
  { aseguradora: 'COLMENA', ramo: 'TRC', disponible: 'no', nota: null },
  { aseguradora: 'COLMENA', ramo: 'DECENAL', disponible: 'no', nota: null },
  { aseguradora: 'COLMENA', ramo: 'D&O', disponible: 'no', nota: null },
  { aseguradora: 'COLMENA', ramo: 'RC SERVIDORES PUBLICOS', disponible: 'no', nota: null },
  { aseguradora: 'COLMENA', ramo: 'CUMPLIMIENTO', disponible: 'no', nota: null },
  { aseguradora: 'METLIFE', ramo: 'PYME (TODO RIESGO)', disponible: 'no', nota: null },
  { aseguradora: 'METLIFE', ramo: 'AUTOS INDIVIDUAL', disponible: 'no', nota: null },
  { aseguradora: 'METLIFE', ramo: 'AUTOS COLECTIVOS', disponible: 'no', nota: null },
  { aseguradora: 'METLIFE', ramo: 'MAQUINARIA', disponible: 'no', nota: null },
  { aseguradora: 'METLIFE', ramo: 'MOTO', disponible: 'no', nota: null },
  { aseguradora: 'METLIFE', ramo: 'TRC', disponible: 'no', nota: null },
  { aseguradora: 'METLIFE', ramo: 'DECENAL', disponible: 'no', nota: null },
  { aseguradora: 'METLIFE', ramo: 'D&O', disponible: 'no', nota: null },
  { aseguradora: 'METLIFE', ramo: 'RC SERVIDORES PUBLICOS', disponible: 'no', nota: null },
  { aseguradora: 'METLIFE', ramo: 'CUMPLIMIENTO', disponible: 'no', nota: null },
  { aseguradora: 'SOLUNION', ramo: 'PYME (TODO RIESGO)', disponible: 'no', nota: null },
  { aseguradora: 'SOLUNION', ramo: 'AUTOS INDIVIDUAL', disponible: 'no', nota: null },
  { aseguradora: 'SOLUNION', ramo: 'AUTOS COLECTIVOS', disponible: 'no', nota: null },
  { aseguradora: 'SOLUNION', ramo: 'MAQUINARIA', disponible: 'no', nota: null },
  { aseguradora: 'SOLUNION', ramo: 'MOTO', disponible: 'no', nota: null },
  { aseguradora: 'SOLUNION', ramo: 'TRC', disponible: 'no', nota: null },
  { aseguradora: 'SOLUNION', ramo: 'DECENAL', disponible: 'no', nota: null },
  { aseguradora: 'SOLUNION', ramo: 'D&O', disponible: 'no', nota: null },
  { aseguradora: 'SOLUNION', ramo: 'RC SERVIDORES PUBLICOS', disponible: 'no', nota: null },
  { aseguradora: 'SOLUNION', ramo: 'CUMPLIMIENTO', disponible: 'no', nota: null },
  { aseguradora: 'EQUIDAD SEGUROS', ramo: 'copropiedades', disponible: 'no', nota: 'NO solo renovaciones 9/05/2026' },
  { aseguradora: 'EQUIDAD SEGUROS', ramo: 'D&O', disponible: 'condicionado', nota: 'CONDICIONADO' },
  { aseguradora: 'EQUIDAD SEGUROS', ramo: 'RC SERVIDORES PUBLICOS', disponible: 'condicionado', nota: 'CONDICIONADO' },
  { aseguradora: 'EQUIDAD SEGUROS', ramo: 'CUMPLIMIENTO', disponible: 'no', nota: null },
]
